### ISSUE TITLE
No Outcomes - PLP Error

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PheValuator#15]
Hi,

I encountered this error with the latest package. Is it due to our data? But should that result in error like below?

`
Error in PatientLevelPrediction::getPlpData(connectionDetails, cdmDatabaseSchema = paste(cdmDatabaseSchema,  : 
  No Outcomes
`

I did come across this issue in the OHDSI forum [https://forums.ohdsi.org/t/phevaluator-faqs/9706/8](url) here. But guess the your response to another issue no 16, can help me understand why is this happening

**Comment by jswerdel** [comment]
The no outcomes error may occur when the xSpec cohort is missing or misspecified in the function call.  It may also be that the xSpec was not generated in the dataset analyzed by the function call.  In that case, the tool would not find any xSpec subjects to include in the model.

**Comment by SSMK-wq** [comment]
This issue can be closed. Thanks
