### ISSUE TITLE
CreateEvaluationCohort - xSensCohort parameter is missing

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PheValuator#17]
Hi,

I was trying to execute the CreateEvaluationCohort and found out that XSens Cohort is mandatory argument for this function but it is missing in the doc and tutorials.

The below is the error message that I got

`Error in PheValuator::createEvaluationCohort(connectionDetails = connectionDetails,  : 
  argument "xSensCohort" is missing, with no default`

However after including this parameter, the error doesn't occur anymore

**Comment by jswerdel** [comment]
I will correct the documentation.  Thanks you for pointing this out.
