### ISSUE TITLE
Time taken to create Phenotype model features

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PheValuator#21]
Hello @jswerdel,

May I check with you on how long can it take to createPhenoTypeModel? I understand it could depend on dataset size but our dataset size is only 5200.

When I execute my XSpec cohort in Atlas, it takes **20 mins** to produce the output (4786) **in Atlas** and XSens cohort also takes **20 mins** to produce the output (3540) **in Atlas**. too many rules. might be it's taking time due to that.

**But will the Atlas cohort creation time affect `CreatePhenotypeModel` function execution as well?**

Because for 4200~4700 cases, it is taking more than an hour and still not done yet. stuck on 24% for a long time.

![image](https://user-images.githubusercontent.com/30723825/76295664-fd9f4200-62ef-11ea-8ac0-eb7e63f4828f.png)

I tried both in laptop and desktop, it's the same. 

Or is it because I have around 15-20K concepts to exclude? Meaning I have only parents concepts.

Is that why it's taking longer time? I tried with **both concept_identifier_list and included_concept_identifier_list**.

Though I have "AddDescendentstoExclude=True", model throws NULL warning when I use "concept_identifier_list".

Whereas when I use "Included_concept_identifier_list", it works but still under execution for a long time?

Is it expected?

Can help me understand this?

**Comment by jswerdel** [comment]
The cohort generation and the feature extraction both pull from the same database so it it likely your database is tied up with other users pulling data.  Both of those things for 4-5K should be much faster - within minutes.

**Comment by SSMK-wq** [comment]
Actually, its only me who is accessing the database right now. No one else is using it.

**Comment by SSMK-wq** [comment]
Actually, its only me who is accessing the db right now and it's again stuck in 24%

Though I have "AddDescendentstoExclude=True", model throws NULL warning when I use "concept_identifier_list".  But this shouldn't throw this warning. Am I right? Because I have used concepts and descendants as well.

Whereas when I use "Included_concept_identifier_list", it works but still under execution for a long time.

Is there any log which I can see to know what's happening?

**Comment by jswerdel** [comment]
I'm confused about using concept_identifier_list and Included_concept_identifier_list. 
The parameter in the function is excludedConcepts

**Comment by SSMK-wq** [comment]
Hi @jswerdel , 

Yes to provide the list of concepts which has to be excluded, I have copied the concepts from Atlas.

I copy the concept_ids from here. I tried with "concept identifier list" and "included concept identifier list"

![image](https://user-images.githubusercontent.com/30723825/76302212-8b802a80-62fa-11ea-8b4d-f0d5ee642f35.png)

**Comment by jswerdel** [comment]
you can use concept identifier list but set AddDescendentstoExclude = TRUE (all caps)

**Comment by SSMK-wq** [comment]
Yeah, but it results in NULL for prediction. Remember the warning message that we discussed

**Comment by jswerdel** [comment]
That's because of your dataset - you have > 90% cases (see prevalence) - the model likely can't be built with so many cases and so few non-cases.  PheValuator can't be used on the dataset as you have developed it.

**Comment by SSMK-wq** [comment]
Okay I get it. But may I kindly check for the below scenario. Please note it's not "concept identifier list" but "Included concept identifier list"

![image](https://user-images.githubusercontent.com/30723825/76304531-7dcca400-62fe-11ea-842d-86aa682b5d85.png)

When I use "**included concept identifier list" and "AddDescendentstoExclude = TRUE**", the 
function **starts execution without any warning but unfortunately stuck at 24%**

Hope this helps to see the difference between "concept identifier list" and "included concept identifier list"

Don't I have to see the same warning message ? Because I believe it is dealing with the same scenario of more positive cases and low negative cases. Right?

**Comment by jswerdel** [comment]
Does it work when you use "concept identifier list"  (the upper list on the ATLAS screen) and "AddDescendentstoExclude = TRUE"?

**Comment by SSMK-wq** [comment]
No, it throws the warning message. Prediction NULL / No non-zero coefficients etc

**Comment by jswerdel** [comment]
that sounds right, when it completes the data extraction and tries to run the model it fails as expected.  I think that when you use "included concept identifier list" (the longer of the 2 lists) and "AddDescendantstoExclude = TRUE" the process is stalling  on the data extraction possibly because your query is longer and more complex - you are trying to find the descendants for a much longer list of concepts - maybe your system cannot support that?

**Comment by SSMK-wq** [comment]
This issue can be closed. Thanks a ton for answering my questions
