### ISSUE TITLE
ML models in Phevaluator 

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PheValuator#24]
Hello, 

Does PheValuator currently only support below settings

a)  Lasso model 
b)  75:25 train test split 
c)  Default hyperparameters for lasso? 

Other models will be in upcoming versions?  Or we can change models in current version as well.  I don't see any function parameter to change though

**Comment by jswerdel** [comment]
Currently the tool only uses LASSO with it's default settings.  We are currently testing other classifiers but we have not found any that out-performs LASSO as yet.

**Comment by SSMK-wq** [comment]
This issue can be closed.  Thank you
