### ISSUE TITLE
Unable to run Chronic Phenotype Model

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/PheValuator#26]
Hello @jswerdel ,

I see that you have modified the package and it's functions. Thanks for your effort.  

But while I was trying to run the `createChronicPhenotypeModel`, I had the below error

> 2020-03-30 17:04:02	Coercing LHS to a list
> 2020-03-30 17:04:02	Coercing LHS to a list
> Connecting using PostgreSQL driver
> 
> Constructing the at risk cohort
>   |==========================================================================================================================| 100%
> Executing SQL took 0.073 secs
> Fetching cohorts from server
> Loading cohorts took 0.316 secs
> Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
>   org.json.JSONException: JSONObject["temporal"] is not a Boolean.

**Comment by jswerdel** [comment]
We have updated the package with new functions.  createChronicPhenotypeModel has been replaced.  I will update the documentation within the next hour.  Please refer to the new documentation for using this package.  Sorry for the problem.

**Comment by SSMK-wq** [comment]
This issue can be closed. Thanks
