### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PheValuator#37]
Version 2.2.5 has just been released, but [NEWS.md](https://github.com/OHDSI/PheValuator/blob/main/NEWS.md) doesn't go further than v 2.2.3. And the [package website](https://ohdsi.github.io/PheValuator/news/index.html) hasn't been regenerated since v2.1.14.

Before releasing a new version, don't forget to update NEWS.md, and run [this code in PackageMaintenance.R](https://github.com/OHDSI/PheValuator/blob/main/extras/PackageMaintenance.R#L24-L35) to update the PDF documents and website.

**Comment by jswerdel** [comment]
All documentation has been completed.
