### ISSUE TITLE
Function and argument naming

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PheValuator#4]
Not all function and argument names are in line with the [OHDSI code style](https://www.ohdsi.org/web/wiki/doku.php?id=development:ohdsi_code_style_for_r). For example, `estPPV` should be `estPpv`.

Also, I **highly** recommend avoiding abbreviations when possible to make code easier to read. For example:

- `estPpv` could be `estimatedPpv`
- `createPhenoModel` could be `createPhenotypeModel`
- `exclCohort` could be `xSensCohort`
- `mainPopnCohort` could be ? (not sure what this argument does)

etc.

**Comment by jswerdel** [comment]
These have all been corrected in version 1.0
