### ISSUE TITLE
Defaulting arguments to "" is not helpful

### ISSUE THREAD

**Issue by schuemie** [OHDSI/PheValuator#6]
For example [here](https://github.com/OHDSI/PheValuator/blob/master/R/CreatePhenoModel.R#L69). If an argument is required, give it a sensible default value if it exists, or else do not give it a default value. (e.g. `xSpecCohort, `

If it is not required, default it to NULL.

Currently the RStudio code issue highlighter doesn't indicate a problem if a user leave's out a required argument.

**Comment by jswerdel** [comment]
These were all changed in the PheValuator functions fro version 1.0
